#!/bin/bash

if [[ ! "$(id -u)" = '0' ]]; then
  echo "YOU ARE NOT ROOT, FAILED" 1>&2
  exit 1
fi

# I am very unhappy that Bind9 does not support the option to treat the bare domain name,
# i.e. example.com, as a record type that can be forwarded while all of the subdomains
# within a zone are then controlled by that zone. Thankfully this hacky method will do.

for dir in /etc/duckdns/*; do
  domain="$(cat "${dir}"/domain).duckdns.org"
  resolves_to="$(dig "${domain}" @1.1.1.1 | grep -v '^\;' | grep "${domain}\." | awk '{print $5}' | head -n 1)"
  sed -i "/${domain}/d" /etc/hosts
  echo "${resolves_to}	${domain}" >> /etc/hosts
  unset resolves_to
  unset domain
done
