#!/bin/bash

#set -eu
set -mxeuo pipefail

ldap_login=/etc/outofband/ldap_password
myhostname="$(hostnamectl --json=pretty | jq -r .Hostname)"

if [[ "$(id -u)" != "0" ]]; then
	echo "You are not root so the script may fail" 2>&1
	exit 2
fi

curl --silent -X POST \
    -H "X-Vault-Request: true" \
    -d "{\"password\":\"$(cat "${ldap_login}")\"}" \
    https://vault.home.arpa:8200/v1/auth/ldap/login/user_"${myhostname}" | \
    jq -r '.auth.client_token' > /etc/outofband/vault_token

curl --silent \
    --header "X-Vault-Token: $(cat /etc/outofband/vault_token)" \
    --data "{\"token\": \"$(cat /etc/outofband/vault_token)\"}" \
    https://vault.home.arpa:8200/v1/auth/token/lookup | \
    jq -r '.data.accessor' > /etc/outofband/vault_token_accessor
