#!/bin/bash

#set -euo pipefail

i=0
check=""
init="false"
sealed="true"

until [[ "${init}" == "true" ]] && [[ "${sealed}" == "false" ]]; do
  if (( i == 99 )); then
    exit 1;
  fi
  check="$(curl --silent https://vault.home.arpa:8200/v1/sys/health)"
  init="$(jq .initialized <<< "${check}")"
  sealed="$(jq .sealed <<< "${check}")"

  sleep $((20 + (RANDOM % 20)))
  i=$((i + 1))
done

exit 0
