#!/bin/bash

#set -eu
set -mxeuo pipefail

ldap_login=/etc/outofband/ldap_password
myhostname="$(hostnamectl --json=pretty | jq -r .Hostname)"

if [[ "$(id -u)" != "0" ]]; then
	echo "You are not root so the script may fail" 2>&1
	exit 2
fi

if [[ -z "${1}" ]]; then
	echo "You did not supply a directory of config files" 1>&2
	exit 1
fi

curl --silent -X POST \
    -H "X-Vault-Request: true" \
    -d "{\"password\":\"$(cat "${ldap_login}")\"}" \
    https://vault.home.arpa:8200/v1/auth/ldap/login/"${myhostname}" | \
    jq -r '.auth.client_token'
